all: FibNodeStructure FibonacciHeap hashtagcounter

FibNodeStructure: 
		javac FibNodeStructure.java
		
FibonacciHeap: 
		javac FibonacciHeap.java
		
hashtagcounter: 
		javac hashtagcounter.java

clean:
		rm *.class